# In order to override the following configurations :
# java -jar keys.jar --spring.config.location=classpath:/application.yml,file:./application-prod.yml
spring:
  application:
    name: "keys"
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
#  ssl:
#    key-store: file:/home/plaplante/CHUST/projects/kidsfirst/kf-key-management-fork/ssl/plaplante.p12
#    key-password: changeit
#    # JKS or PKCS12
#    key-store-type: PKCS12
  servlet:
    session:
      cookie:
        http-only: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: "application/json"
application:
  debug: false
  # Pipe delimited list of allowed domains.
  cors_allowed_domains: "https://portal-qa.kidsfirstdrc.org"
  aspect:
    enabled: true
#  dynamodb:
#    endpoint: "http://localhost:8000"
  cavatica_root: "https://pgc-accounts.sbgenomics.com/v2"
  secret_table: "kf-key-management-secret"
  fence:
    dcf:
      client_id: "Jue4ZBwbuqK87nYbEWldwED7CxER7CgDt2I8a87Q"
      client_secret: "__TBD__"
      token_endpoint: "https://kf-key-manager.kidsfirstdrc.org/token?service=dcf"
      redirect_uri: "https://portal.kidsfirstdrc.org/dcf_redirect/"
      scope: "openid"
    gen3:
      client_id: "V3TPPDDL2T180uPTGy0bZID114KPsd0jczi0DoxV"
      client_secret: "__TBD__"
      token_endpoint: "https://kf-key-manager.kidsfirstdrc.org/token?service=gen3"
      redirect_uri: "https://portal.kidsfirstdrc.org/gen3_redirect/"
      scope: "openid"
  kms: "__KMS_KEY_TBD__"

keycloak:
  realm: "kidsfirstdrc"
  auth-server-url: "https://kf-keycloak-qa.kf-strides.org/auth"
  ssl-required: "external"
  resource: "kidsfirst-apis"
  bearer-only: true
  confidential-port: 0